Repository lion-packages/mailer, pull requests merged in 2024-11, with the labels that each got.

#11 Support and maintenance
  CODE_OF_CONDUCT.md
  Dockerfile
  README.md
  composer.json
  composer.lock
  phpunit.xml
Labels: continuous integration, dependencies

#12 Fixed constant calls
  src/MailerAccountConfig.php
Labels: bug

#13 Support with PHP 8.4
  Dockerfile
Labels: continuous integration
