Repository lion-packages/mailer, pull requests merged in 2025-03, with the labels that each got.

#17 Update PHPUnit v12
  Dockerfile
  composer.json
  phpunit.xml
Labels: dependencies

#19 build:phpstan and phpcodesniffer are installed
  composer.json
Labels: dependencies

#20 phpstan and php_codesniffer are standardized
  composer.json
  src/Accounts/PHPMailerAccount.php
  src/Accounts/SymfonyMailerAccount.php
  src/Exceptions/InvalidRecipientAddressException.php
  src/Mailer.php
  src/MailerAccountConfig.php
  src/MailerAccountInterface.php
  tests/MailerAccountsTest.php
  tests/MailerTest.php
  tests/Provider/MailerProviderTrait.php
  tests/build/coverage/.gitignore
  tests/build/logs/.gitignore
Labels: enhancement, dependencies

#21 Docker configuration is updated
  Dockerfile
Labels: continuous integration

#18 add workflow
  .env.actions
  .env.example
  .github/workflows/php.yml
  .gitignore
  composer.json
  phpunit.xml
  tests/MailerAccountsTest.php
  tests/bootstrap.php
Labels: continuous integration

#22 The project files are organized
  composer.json
  src/LionMailer/AccountType.php
  src/LionMailer/Accounts/PHPMailerAccount.php
  src/LionMailer/Accounts/SymfonyMailerAccount.php
  src/LionMailer/Exceptions/EmptyBodyException.php
  src/LionMailer/Exceptions/InvalidFromAddressException.php
  src/LionMailer/Exceptions/InvalidRecipientAddressException.php
  src/LionMailer/Exceptions/MailerAccountConfigException.php
  src/LionMailer/Mailer.php
  src/LionMailer/MailerAccountConfig.php
  src/LionMailer/MailerAccountInterface.php
  src/LionMailer/Priority.php
Labels: enhancement, dependencies

#23 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#27 Update README.md
  .github/README.md
Labels: documentation
