Repository lion-packages/mailer, pull requests merged in 2025-04, with the labels that each got.

#28 Installation of Infection
  composer.json
  infection.json
  phpunit.xml
  src/LionMailer/Accounts/PHPMailerAccount.php
  src/LionMailer/Accounts/SymfonyMailerAccount.php
  src/LionMailer/Exceptions/EmptyBodyException.php
  src/LionMailer/Exceptions/InvalidFromAddressException.php
  src/LionMailer/Exceptions/InvalidRecipientAddressException.php
  src/LionMailer/Exceptions/MailerAccountConfigException.php
  src/LionMailer/Mailer.php
  src/LionMailer/MailerAccountConfig.php
  tests/Exceptions/EmptyBodyExceptionTest.php
  tests/Exceptions/InvalidFromAddressExceptionTest.php
  tests/Exceptions/InvalidRecipientAddressExceptionTest.php
  tests/Exceptions/MailerAccountConfigExceptionTest.php
  tests/MailerAccountsTest.php
  tests/MailerTest.php
  tests/Provider/MailerAccountsProviderTrait.php
  tests/Provider/MailerProviderTrait.php
  tests/bootstrap.php
Labels: dependencies, tests

#29 Infection is integrated
  .github/workflows/php.yml
  Dockerfile
Labels: continuous integration

#31 Added StyleCI configuration
  .styleci.yml
  src/LionMailer/MailerAccountConfig.php
Labels: enhancement

#32 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#33 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#34 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#35 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration
